skip_commits:
  message: /docs|Merge pull request.*/
image: Visual Studio 2019
build_script:
  - dotnet build src --configuration Release
  - dotnet test src/EfLocalDb.Tests/EfLocalDb.Tests.csproj --configuration Release --no-build --no-restore
  - dotnet test src/EfClassicLocalDb.Tests/EfClassicLocalDb.Tests.csproj --configuration Release --no-build --no-restore
  - dotnet test src/LocalDb.Tests/LocalDb.Tests.csproj --configuration Release --no-build --no-restore
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off
artifacts:
- path: nugets\**\*.nupkg